name: 🐛 Bug report
description: Сообщить о проблеме или ошибке в библиотеке
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить Bug report! 😊
  - type: textarea
    id: what-happened
    attributes:
      label: 📝 Опишите ошибку
      description: Четкое и краткое описание ошибки и любой дополнительный контекст.
      placeholder: Расскажите нам, что вы видите! 👀
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: 🔄 Как воспроизвести
      description: Шаги для воспроизведения проблемы.
      placeholder: |
        1. Получить '...' 📥
        2. Обновить '....' 🔄
        3. Увидеть ошибку ⚠️
    validations:
      required: true
  - type: textarea
    id: code-snippets
    attributes:
      label: 💻 Фрагменты кода
      description: Если применимо, добавьте фрагменты кода, чтобы помочь объяснить проблему.
      render: Python
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: 🖥️ Операционная система
      placeholder: macOS
    validations:
      required: true
  - type: input
    id: language-version
    attributes:
      label: 🐍 Версия Python
      placeholder: Python v3.11.4
    validations:
      required: true
  - type: input
    id: lib-version
    attributes:
      label: 📚 Версия библиотеки
      placeholder: evolution-openai v0.1.0
    validations:
      required: true