name: ✨ Feature request
description: Предложить идею для библиотеки
labels: ['feature-request']
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить Feature request! 🚀
  - type: checkboxes
    id: non_api
    attributes:
      label: ✅ Подтвердите, что это Feature request для Python библиотеки, а не для OpenAI API
      description: Запросы функций для OpenAI API следует сообщать в нашем [Сообществе разработчиков](https://community.openai.com/c/api/7) 👥
      options:
        - label: Это Feature request для Python библиотеки
          required: true
  - type: textarea
    id: feature
    attributes:
      label: 💡 Опишите функцию или улучшение, которое вы запрашиваете
      description: Четкое и краткое описание того, что вы хотите получить.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 📋 Дополнительный контекст
      description: Добавьте любой другой контекст о запросе функции здесь.